import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, breadcrumbs
}: Readonly<{
  children: React.ReactNode, breadcrumbs: React.ReactNode
}>) {
  return (
      
    <html lang="fr">
      <body className={`h-screen flex flex-col ${inter.className} bg-gray-100`}>
        <div className="p-2 px-10 border-b-2 bg">{breadcrumbs }</div>
        <div className="p-2 px-10">{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
